import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The AI Agents in Practice curriculum.
 * Each part is a category autogenerated from its docs/ folder; chapters sort by
 * their NN- filename prefix / sidebar_position.
 */
const sidebars: SidebarsConfig = {
  agents: [
    'intro',
    {
      type: 'category',
      label: 'Part I · Foundations',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'part1-foundations'}],
    },
    {
      type: 'category',
      label: 'Part II · Agent Architectures',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'part2-architectures'}],
    },
    {
      type: 'category',
      label: 'Part III · Building Agents',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'part3-building'}],
    },
    {
      type: 'category',
      label: 'Part IV · Deployment',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'part4-deployment'}],
    },
    {
      type: 'category',
      label: 'Part V · The Business of Agents',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'part5-business'}],
    },
    {
      type: 'category',
      label: 'Appendices',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'appendices'}],
    },
  ],
};

export default sidebars;
