import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The book's table of contents.
 *
 * Each part is a category whose items are autogenerated from its folder, so
 * dropping a new `NN-title.mdx` chapter file into the matching `docs/partX-*`
 * folder adds it to the sidebar automatically. Chapters sort by their
 * `sidebar_position` frontmatter, which mirrors the `NN-` filename prefix.
 *
 * Ordering, labels, and folder names follow the approved book structure in
 * `BOOK-STRUCTURE.md`.
 */
const sidebars: SidebarsConfig = {
  book: [
    'intro',
    {
      type: 'category',
      label: 'Part I · Foundations',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'part1-foundations'}],
    },
    {
      type: 'category',
      label: 'Part II · Sensing & Perception',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'part2-sensing'}],
    },
    {
      type: 'category',
      label: 'Part III · Actuation & Control',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'part3-control'}],
    },
    {
      type: 'category',
      label: 'Part IV · Learning & Intelligence',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'part4-learning'}],
    },
    {
      type: 'category',
      label: 'Part V · Systems, Simulation & Deployment',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'part5-systems'}],
    },
    {
      type: 'category',
      label: 'Part VI · The Road Ahead',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'part6-future'}],
    },
    {
      type: 'category',
      label: 'Appendices',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'appendices'}],
    },
  ],
};

export default sidebars;
